apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a2e99ixzl-go 
  janus-idp.io/tekton: a2e99ixzl-go
  backstage.io/kubernetes-id: a2e99ixzl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a2e99ixzl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml